#!/bin/sh

mkfs.xfs -f /dev/mapper/writeboost-vol
#OPTIONS="-o nobarrier"
mount ${OPTIONS} /dev/mapper/writeboost-vol /mnt/writeboost-vol
rm -rf /mnt/writeboost-vol/*
RUBY=ruby-1.9.3-p362
cp ${RUBY}.tar.gz /mnt/writeboost-vol
cd /mnt/writeboost-vol
tar xvfz ${RUBY}.tar.gz
cd ${RUBY}

./configure

make -j 8
echo 3 > /proc/sys/vm/drop_caches
make test

fuser -muv /mnt/writeboost-vol
umount -l /mnt/writeboost-vol
