#!/bin/sh

mkfs.xfs -f /dev/mapper/perflv 
#OPTIONS="-o nobarrier"
mount ${OPTIONS} /dev/mapper/perflv /mnt/perflv
rm -rf /mnt/perflv/*
RUBY=ruby-1.9.3-p362
cp ${RUBY}.tar.gz /mnt/perflv
cd /mnt/perflv
tar xvfz ${RUBY}.tar.gz
cd ${RUBY}

dmsetup message lc-mgr 0 switch_to 1
dmsetup message lc-mgr 0 clear_stat
./configure

make -j 8
make test
