#! /bin/sh

export WB_ROOT=`pwd`

# Setup this file
# so as to fit your environment.


# Desc (read this first):
#
# (for type >= 0)
# The writeboost device to create
# will cache writes to $BACKING device on $CACHE device.
#
# (for type > 0 only)
# $PLOG is not essential,
# Persistent Logging (plog) is a supplimental structure
# that stablizes writeboost' response.


# backing device (orig_dev) - essential
# BACKING=/dev/hvg2/back18g
BACKING=/dev/vg2/back40g # benchmark
export BACKING

# cache device (cache_dev) - essential
# CACHE=/dev/hvg1/cache2g
# CACHE=/dev/hvg1/cache3m
CACHE=/dev/sdd2 # benchmark
export CACHE

# plog device (plog_dev_desc) - only if type > 0
# PLOG=/dev/hvg1/cache3m
# PLOG=/dev/hvg1/cache2g
PLOG=/dev/loop0 # benchmark
# PLOG=/dev/sdd3 # benchmark
export PLOG

echo BACKING: ${BACKING}
echo CACHE  : ${CACHE}
echo PLOG   : ${PLOG}

# common routines
remove_dev() {
    dmsetup suspend writeboost-vol
    dmsetup resume writeboost-vol
    dmsetup remove writeboost-vol
}
