#! /bin/sh

export WB_ROOT=`pwd`

#BACKING=/dev/vg2/back18g
#BACKING=/dev/vdd
BACKING=/dev/vdd1
#BACKING=/dev/vg2/back40g
#BACKING=/dev/sdc2
export BACKING

#CACHE=/dev/vg1/cache3m
CACHE=/dev/vg1/cache2g
#CACHE=/dev/sdd2
export CACHE

echo BACKING: ${BACKING}
echo CACHE  : ${CACHE}
