#!/bin/sh

. ./config

echo 7 > /proc/sys/kernel/printk

# Discard the whole cache device before formatting
# blkdiscard command is included in upstream util-linux.
# But don't worry, without discarding, dm-lc works correctly.
# This is only a performance-relevant issue.
blkdiscard --offset 0 --length `blockdev --getsize64 ${CACHE}` ${CACHE}

# Zeroing the first sector in the cache device
# triggers formatting the cache device
echo destory cache ... 
dd if=/dev/zero of=${CACHE} bs=512 count=1 oflag=direct

echo create writeboost-vol ...
sz=`blockdev --getsize ${BACKING}`
# dmsetup create writeboost-vol --table "0 ${sz} writeboost ${BACKING} ${CACHE} 11 8192"
dmsetup create writeboost-vol --table "0 ${sz} writeboost ${BACKING} ${CACHE}"

if test $? -ne 0; then
    echo "initialization failed. see dmseg"
    exit
fi

echo configure things for tests ...
# dmsetup message writeboost-vol 0 barrier_deadline_ms 1000
# dmsetup message writeboost-vol 0 enable_migration_modulator 1
# dmsetup message writeboost-vol 0 update_record_interval 2
# dmsetup message writeboost-vol 0 sync_interval 3

# To disable migration except urgent ones
# enable these two lines.
# dmsetup message writeboost-vol 0 enable_migration_modulator 0
# dmsetup message writeboost-vol 0 allow_migrate 0
