#!/bin/sh

lc-daemon start

echo lc-detach ...
lc-detach 1

echo lc-remove ...
lc-remove 1

echo lc-daemon stop ...
lc-daemon stop

echo lc-free-cache ...
lc-free-cache

cd Driver
make uninstall
cd -
