#!/bin/sh

# Description
# -----------
# 1. write many files with cache device
# 2. detach cache without all dirty data migrated
# 3. mount the filesystem without cache device

. ../../config

dd if=/dev/zero of=${CACHE} bs=512 count=1 oflag=direct
sz=`blockdev --getsize ${BACKING}`
dmsetup create writeboost-vol --table "0 ${sz} writeboost 0 ${BACKING} ${CACHE} 2 segment_size_order 10 2 allow_migrate 1"

#mkfs.xfs -f /dev/mapper/writeboost-vol > /dev/null
mkfs.ext4 /dev/mapper/writeboost-vol > /dev/null

# migrate the initial metadata of the fs
dmsetup message writeboost-vol 0 drop_caches

mount /dev/mapper/writeboost-vol /mnt/writeboost-vol

rm -rf /mnt/writeboost-vol/*
cd /mnt/writeboost-vol
dd if=/dev/urandom of=orig4k oflag=direct bs=4096 count=16
i=0
while [ $i -ne 1000 ]
do
    i=`expr $i + 1`
    fn=`openssl rand -base64 24 | sed -e s:\/:x:g`
    cp orig4k $fn
done
cd -
echo \# files \(w\\ cache\)
ls /mnt/writeboost-vol | wc -l

dmsetup status writeboost-vol

#dmsetup message writeboost-vol 0 drop_caches

fuser -muv /mnt/writeboost-vol
umount -l /mnt/writeboost-vol
dmsetup remove writeboost-vol

echo mount backing device
mount $BACKING /mnt/writeboost-vol
if  [ $? -ne 0 ]; then
    echo BUG: failed to mount backing device only
fi
echo \# files \(wo cache\)
ls /mnt/writeboost-vol | wc -l
fuser -muv /mnt/writeboost-vol
umount -l /mnt/writeboost-vol
